// Cesium loads its Workers/Assets/Widgets/ThirdParty files relative to this
// base URL at runtime. Required whenever Cesium is included via a plain
// <script> tag (no bundler) rather than npm + a build step.
window.CESIUM_BASE_URL = "https://unpkg.com/cesium@1.144.0/Build/Cesium/";

// ---------------------------------------------------------------------------
// SYNTHETIC POSITIONING (TEMPORARY)
//
// Our building/apartment geometry is generated in a purely local coordinate
// system (x/y roughly 5-25, z = height in meters) — it is NOT real
// longitude/latitude. Cesium's globe only understands real geographic
// coordinates, so we have to anchor the model *somewhere* on Earth to view
// it at all.
//
// This anchor is arbitrary and carries no cadastral meaning. Every apartment
// entity is placed at this SAME anchor, so their original relative local
// coordinates (which is all that matters for the building to look correct)
// are preserved exactly as generated by apartment.py. Everything
// geo-referencing-related is isolated in this one function so it can be
// swapped for real parcel lon/lat/elevation later without touching any of
// the Cesium viewer/model-loading logic below.
// ---------------------------------------------------------------------------
function getSyntheticModelOrigin() {
  // Arbitrary anchor point, for visualization only.
  const longitude = 75.7873; // placeholder, not derived from cadastral data
  const latitude = 26.9124;  // placeholder, not derived from cadastral data
  const height = 0;

  return Cesium.Cartesian3.fromDegrees(longitude, latitude, height);
}

// ---------------------------------------------------------------------------
// APARTMENT IDENTIFICATION
//
// apartment.py now exports one GLB per apartment (data/synthetic/apartments/
// <unit_id>.glb) plus data/synthetic/apartments_metadata.json, a mapping of
// property_id -> metadata. We load one Cesium Entity per apartment GLB and
// set the entity's id to the unit_id, so a click directly resolves to the
// correct property with no coordinate/hardcoding logic involved: Cesium's
// picker returns the picked entity, and `entity.id` is the property id we
// already generated in Python.
// ---------------------------------------------------------------------------

const DEFAULT_COLOR = Cesium.Color.fromCssColorString("#c7c7c7");
const HIGHLIGHT_SILHOUETTE = Cesium.Color.fromCssColorString("#ffcc00");

let selectedEntity = null;

function fieldRow(label, value) {
  const row = document.createElement("div");
  row.className = "row";

  const dt = document.createElement("dt");
  dt.textContent = label;

  const dd = document.createElement("dd");
  dd.textContent = value;

  row.appendChild(dt);
  row.appendChild(dd);
  return row;
}

function showInfoPanel(metadata) {
  const panel = document.getElementById("infoPanel");
  const body = document.getElementById("infoPanelBody");

  body.innerHTML = "";
  body.appendChild(fieldRow("Property ID", metadata.property_id));
  body.appendChild(fieldRow("Building ID", metadata.building_id));
  body.appendChild(fieldRow("Floor", metadata.floor));
  body.appendChild(fieldRow("Unit", metadata.unit));
  body.appendChild(fieldRow("Area", `${metadata.area.toFixed(1)} m²`));
  body.appendChild(fieldRow("Height", `${metadata.height.toFixed(1)} m`));
  body.appendChild(fieldRow("Volume", `${metadata.volume.toFixed(1)} m³`));
  body.appendChild(fieldRow("Watertight", metadata.watertight ? "True" : "False"));
  body.appendChild(fieldRow("Geometry", metadata.geometry_valid ? "Valid" : "Invalid"));

  panel.classList.remove("hidden");
}

function hideInfoPanel() {
  document.getElementById("infoPanel").classList.add("hidden");
}

function clearSelection() {
  if (selectedEntity) {
    selectedEntity.model.silhouetteSize = 0;
    selectedEntity = null;
  }
}

function selectEntity(entity) {
  clearSelection();
  entity.model.silhouetteColor = HIGHLIGHT_SILHOUETTE;
  entity.model.silhouetteSize = 4;
  selectedEntity = entity;
}

async function loadApartmentEntities(viewer, origin) {
  const metadataResponse = await fetch("../data/synthetic/apartments_metadata.json");
  if (!metadataResponse.ok) {
    throw new Error(`Could not load apartments_metadata.json (${metadataResponse.status})`);
  }
  const metadataByUnit = await metadataResponse.json();

  const unitIds = Object.keys(metadataByUnit);

  // Every apartment GLB's own vertices already encode the real local
  // building coordinates (x/y in-plane, z = height, generated in
  // apartment.py) — that's what makes the floors stack correctly. But an
  // Entity's model is only ever rotated straight from that local
  // coordinate space into Earth-Centered-Earth-Fixed (ECEF) axes, not into
  // "up at this point on the globe". If we don't set `orientation`
  // explicitly, Cesium defaults to the ECEF identity quaternion, so the
  // model's local Z (our height axis) ends up pointing towards the North
  // Pole instead of straight up at our anchor's latitude — which is why
  // the whole 7-floor stack was rendering almost flattened/sideways.
  // Computing the east-north-up quaternion at the anchor makes local
  // x/y/z line up with true east/north/up there, so height stacks
  // vertically as intended.
  const orientation = Cesium.Transforms.headingPitchRollQuaternion(
    origin,
    new Cesium.HeadingPitchRoll(0, 0, 0)
  );

  for (const unitId of unitIds) {
    viewer.entities.add({
      id: unitId,
      name: unitId,
      position: origin,
      orientation: orientation,
      model: {
        uri: `../data/synthetic/apartments/${unitId}.glb`,
        scale: 1.0,
        minimumPixelSize: 64,
        // Mute the flat, fully-saturated per-apartment colors baked in by
        // trimesh toward a neutral concrete/facade tone, blended (not
        // replaced) so units are still faintly distinguishable at a glance.
        // This is purely a display tweak — the GLB's own colors are
        // untouched, so nothing about apartment.py needs to change.
        color: DEFAULT_COLOR,
        colorBlendMode: Cesium.ColorBlendMode.MIX,
        colorBlendAmount: 0.8,
      },
    });
  }

  return metadataByUnit;
}

async function init() {
  const loadingEl = document.getElementById("loading");

  const viewer = new Cesium.Viewer("cesiumContainer", {
    baseLayerPicker: false,
    geocoder: false,
    homeButton: false,
    sceneModePicker: false,
    navigationHelpButton: false,
    animation: false,
    timeline: false,
    fullscreenButton: false,
    infoBox: false,
    selectionIndicator: false,
    // Bundled offline imagery — avoids requiring a Cesium ion access token
    // for this MVP. Swap for World Imagery + an ion token later if desired.
    imageryProvider: new Cesium.TileMapServiceImageryProvider({
      url: Cesium.buildModuleUrl("Assets/Textures/NaturalEarthII"),
    }),
  });

  try {
    const origin = getSyntheticModelOrigin();

    loadingEl.textContent = "Loading apartments…";
    const metadataByUnit = await loadApartmentEntities(viewer, origin);

    // Frame the camera around the whole building once every apartment
    // entity has been added. A plain zoomTo() tends to settle in a near
    // top-down view for a building that's wide relative to its height —
    // from directly above, every lower floor is hidden underneath the
    // floor above it (same as a real building), so it can look like only
    // the top floor exists. Flying to the bounding sphere with an explicit
    // oblique pitch guarantees the side faces (and the floor stacking)
    // are visible by default; the user can still freely orbit from there.
    await viewer.zoomTo(
      viewer.entities,
      new Cesium.HeadingPitchRange(
        Cesium.Math.toRadians(35),   // heading: slight rotation, so more than one facade is visible
        Cesium.Math.toRadians(-30),  // pitch: oblique downward angle instead of near-vertical
        0                             // range: 0 lets Cesium pick a distance that fits the bounding sphere
      )
    );
    loadingEl.classList.add("hidden");

    document.getElementById("infoPanelClose").addEventListener("click", () => {
      clearSelection();
      hideInfoPanel();
    });

    // Click-to-identify: pick the apartment entity under the cursor,
    // highlight it, and show its metadata (looked up by the entity's id,
    // which is the property_id generated in apartment.py).
    const handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
    handler.setInputAction((click) => {
      const picked = viewer.scene.pick(click.position);
      const entity = picked && picked.id;

      if (entity && entity.model && metadataByUnit[entity.id]) {
        selectEntity(entity);
        showInfoPanel(metadataByUnit[entity.id]);
      } else {
        clearSelection();
        hideInfoPanel();
      }
    }, Cesium.ScreenSpaceEventType.LEFT_CLICK);
  } catch (error) {
    console.error("Failed to load apartments:", error);
    loadingEl.textContent = "Failed to load model — see console for details.";
    loadingEl.classList.add("error");
  }
}

init();